--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NopeNotDark/BetterModeration
build-by-default: true
branches:
- main
projects:
  BetterModeration:
    path: ""
    icon: "logo.png"
    libs:
      - src: muqsit/invMenu/invMenu
        version: 4.6.1
      - src: poggit/libasynql/libasynql
        version: 4.1.6
...
