--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NopeNotDark/BetterModeration
build-by-default: true
branches:
- main
projects:
  BetterModeration:
    path: ""
    logo: "logo.png"
...
